name: plenoptic_docs

channels:
  - conda-forge

dependencies:
  - sphinx
  - sphinx_rtd_theme
  - numpydoc
  - numpy
  - python
  - pip
  - ipython
  # to avoid https://github.com/matplotlib/matplotlib/issues/20656
  - matplotlib >= 3.7
  - pip:
    - nbsphinx
    - nbsphinx_link
    - sphinxcontrib-apidoc
    - sphinx-autodoc-typehints
