name: plenoptic_docs

channels:
  - conda-forge

dependencies:
  - sphinx
  - sphinx_rtd_theme
  - numpydoc
  - numpy
  - python
  # test
  - pip
  - ipython
  - pip:
    - nbsphinx
    - nbsphinx_link
    - sphinxcontrib-apidoc
    - sphinx-autodoc-typehints
