name: build
on:
  schedule:
    - cron: "0 0 * * 0" # weekly
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
        test_script: ['metamers', 'models', 'plenoptic', 'steerable_pyr', 'eigendistortion', 'mad', 'display']
      fail-fast: false
    name: CI
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install -e .
          pip install pytest-cov
          sudo apt update
          sudo apt install ffmpeg
      - name: Run tests with pytest
        run: 'pytest --cov=plenoptic tests/test_${{ matrix.test_script }}.py'
      - name: Upload to codecov
        run: 'bash <(curl -s https://codecov.io/bash)'
