# .github/workflows/notebooks.yml
# Run all notebooks on every PR and weekly
name: tutorials
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0" # weekly
  pull_request:
    branches:
      - main

jobs:
  # based on https://slashgear.github.io/how-to-split-test-by-folder-with-github-action/
  get_notebooks:
    runs-on: ubuntu-latest
    outputs:
      notebook: ${{ steps.get-notebooks.outputs.nb }}
    steps:
      - uses: actions/checkout@v2
      - id: get-notebooks
        # it's weird to me, but the quotes around \n should *not* be escaped or it breaks
        run: echo "::set-output name=nb::$(ls examples/*ipynb | jq -R -s -c 'split("\n")[:-1]')"
  run:
    runs-on: ubuntu-latest
    needs: [get_notebooks]
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
        notebook: ${{fromJson(needs.get_notebooks.outputs.notebook)}}
      fail-fast: false
    name: Execute notebooks
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: setup.py
      - name: Setup FFmpeg
        uses: FedericoCarboni/setup-ffmpeg@v1
      - name: Install dependencies
        # nbclient 0.5.5 is the first version that includes jupyter execute
        run: |
          pip install --upgrade --upgrade-strategy eager -e .
          pip install jupyter ipywidgets
          pip install "nbclient>=0.5.5"
      - name: Run notebooks
        if: ${{ matrix.notebook != 'examples/Demo_Eigendistortion.ipynb' }}
        run: "jupyter execute ${{ matrix.notebook }}.ipynb --kernel_name=python3"
      - name: Run notebooks
        if: ${{ matrix.notebook == 'examples/Demo_Eigendistortion.ipynb' }}
        # this notebook takes much longer than the rest (if run to completion,
        # ~1hr on a laptop, more than 5 hours on the Github runners). We use
        # papermill's parameters to reduce the max number of steps for
        # eigendistortion synthesis here (we want to test that each cell runs,
        # but we don't need synthesis to go to completion)
        run: |
          pip install --upgrade --upgrade-strategy eager papermill
          papermill ${{ matrix.notebook }} examples/Demo_Eigendistortion_output.ipynb -p max_steps_frontend 10 -p max_steps_vgg 10 -k python3
