# .github/workflows/notebooks.yml
# Run all notebooks on every PR and weekly
name: tutorials
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0" # weekly
  pull_request:
    branches:
      - main

jobs:
  # based on https://slashgear.github.io/how-to-split-test-by-folder-with-github-action/
  get_notebooks:
    runs-on: ubuntu-latest
    outputs:
      notebook: ${{ steps.get-notebooks.outputs.nb }}
    steps:
      - uses: actions/checkout@v2
      - id: get-notebooks
        # it's weird to me, but the quotes around \n should *not* be escaped or it breaks
        run: echo "::set-output name=nb::$(ls examples/*ipynb | jq -R -s -c 'split("\n")[:-1]')"
  run:
    runs-on: ubuntu-latest
    needs: [get_notebooks]
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
        notebook: ${{fromJson(needs.get_notebooks.outputs.notebook)}}
      fail-fast: false
    name: Execute notebooks
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      # based on AllenNLP's setup:
      # https://medium.com/ai2-blog/python-caching-in-github-actions-e9452698e98d
      - name: Cache environment
        uses: actions/cache@v2
        with:
          # Cache the Python package environment, excluding pip and setuptools
          # installed by setup-python, following
          # https://github.com/pypa/pip/issues/9880
          path: |
            ~/.cache/pip
            ${{ env.pythonLocation }}/bin/*
            ${{ env.pythonLocation }}/include
            ${{ env.pythonLocation }}/lib/python*/site-packages/*
            !${{ env.pythonLocation }}/bin/pip*
            !${{ env.pythonLocation }}/lib/python*/site-packages/pipe*
            !${{ env.pythonLocation }}/lib/python*/site-packages/setuptools*
          key: ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}
      - name: Setup FFmpeg
        uses: FedericoCarboni/setup-ffmpeg@v1
      - name: Install dependencies
        # nbclient 0.5.5 is the first version that includes jupyter execute
        run: |
          pip install --upgrade --upgrade-strategy eager -e .
          pip install jupyter ipywidgets
          pip install "nbclient>=0.5.5"
      - name: Run notebooks
        run: "jupyter execute examples/${{ matrix.notebook }}.ipynb --kernel_name=python3"
